/**
 * 证据工作台 API 出口：页面与组件只从此处获取证据数据。
 */

export {
  getEvidenceRepository,
  setEvidenceRepository,
  createEvidenceHttp,
  EvidenceApiError,
  EvidenceDecodeError,
  type EvidenceRepository,
  type EvidenceRequestOptions,
} from "./evidenceRepository";
export { evidencePageImageUrl } from "./evidenceHttp";
export { getEvidenceJobDetail, retryEvidenceJob } from "./evidenceJobHttp";
export type {
  EvidenceJobDetailView,
  EvidenceJobStatusView,
  EvidenceJobProgressView,
} from "./evidenceJobViewModels";
export {
  decodeUploadPreview,
  decodeSnapshot,
  decodeSnapshotList,
  decodeCommitResponse,
  decodeMetadataRevision,
  decodeMetadataRevisionResponse,
  decodeUploadPreviewError,
  decodeJsonValue,
  formatByteSize,
  commitResultMessage,
  type EvidenceItemView,
  type EvidenceUploadPreviewView,
  type EvidenceSnapshotView,
  type EvidenceSnapshotListView,
  type EvidenceSnapshotMemberView,
  type EvidenceCommitView,
  type EvidenceMetadataRevisionView,
  type EvidenceMetadataRevisionResponseView,
  type EvidenceResolutionDecisionView,
  type EvidenceUploadMode,
  type EvidenceItemStatus,
  type EvidencePreviewStatus,
  type EvidenceConflictResolution,
  type EvidenceConflictContext,
} from "./evidenceViewModels";
export type {
  EvidenceCommitRequestWire,
  EvidenceCommitResponseWire,
  EvidenceMetadataRevisionRequestWire,
  EvidenceMetadataRevisionResponseWire,
  EvidenceMetadataRevisionWire,
  CreateUploadPreviewInput,
} from "./evidenceTypes";
export {
  decodeProcessingRevision,
  decodeOcrPage,
  decodeReferencedDocument,
  decodeReferencedDocumentList,
  decodeReferencedDocumentResolution,
  decodeCorrectionResponse,
  decodeRiskReviewResponse,
  decodeRiskPageReviewResponse,
  decodeProcessingCandidateStatus,
  conflictDifferenceRows,
  criticalCorrectionKind,
  criticalCorrectionTextChanged,
  correctionKindLabel,
  clinicalLocatorPrecisionLabel,
  isReviewableLocator,
  type ProcessingRevisionPageView,
  type ProcessingRevisionView,
  type OcrPageView,
  type OcrRiskFlagView,
  type OcrRiskScanView,
  type OcrRiskReviewView,
  type CorrectionView,
  type LocatorView,
  type ReferencedDocumentView,
  type ReferencedDocumentListView,
  type ReferencedDocumentResolutionView,
  type CorrectionCreateResponseView,
  type RiskReviewCreateResponseView,
  type RiskPageReviewCreateResponseView,
  type ProcessingCandidateView,
  type ConflictDifferenceRow,
  type CorrectionChangeKind,
  type OcrRiskReviewDecision,
} from "./evidenceProcessingViewModels";
export type {
  CorrectionCreateRequestWire,
  RiskReviewCreateRequestWire,
  RiskPageReviewCreateRequestWire,
  ReferencedDocumentCreateRequestWire,
  ReferencedDocumentReviseRequestWire,
  ReferencedDocumentConfirmRequestWire,
  ReferencedDocumentDismissRequestWire,
  ReferencedDocumentResolveRequestWire,
} from "./evidenceProcessingTypes";
