"""方案文档提取层（Phase 3 切片 1）。

设计书 §4.1「文档提取器」的结构通道与渲染通道边界：

- ``ingestion``        原始文件登记、SHA-256、MIME/格式检查；
- ``docx_structure``   DOCX 段落/表格/嵌套表格/编号/页眉页脚/section/修订标记；
- ``rendering``        受控 LibreOffice 派生物 PDF 与 manifest；
- ``source_alignment`` 结构块到渲染页/文本范围对齐。

本层只产出 :mod:`app.domain.contracts.protocol_ingestion` 中的不可变合同，
不承载规则语义或发布权威，不写数据库（持久化由上层服务注入仓储完成）。
"""
from __future__ import annotations

from .docx_structure import (
    BlockKind,
    HeaderFooterKind,
    NumberingRef,
    StructureBlock,
    StructureExtraction,
    block_set_hash,
    extract_docx_structure,
    parse_numbering,
    serialize_blocks,
)
from .ingestion import (
    ProtocolFileKind,
    SourceIngestionError,
    compute_sha256,
    detect_format,
    register_source_artifact,
    utc_now,
)
from .rendering import (
    RenderResult,
    build_render_artifact,
    libreoffice_version,
    locate_libreoffice,
    pdf_page_count,
    pdf_page_texts,
    render_to_pdf,
)
from .source_alignment import (
    AlignmentResult,
    align_blocks,
    find_block_by_ref,
    verify_excerpt_against_blocks,
)
from .metadata import (
    MetadataExtractionError,
    MetadataExtractionResult,
    confirm_protocol_identity,
    extract_metadata_candidates,
    extract_protocol_metadata,
    resolve_identity_candidates,
    resolve_protocol_identity,
)
from .phase_detection import (
    PhaseDetectionResult,
    build_phase_applicability_graph,
    detect_phase_applicability,
    project_phase_applicability,
    project_single_phase,
)
from .deconstruction_service import (
    DeconstructionInputAssemblyError,
    ProtocolDeconstructionInputAssembler,
    ProtocolDeconstructionInputAssemblyError,
    ProtocolDeconstructionInputPackage,
    ProtocolInputAssemblyError,
    assemble_deconstruction_input_package,
    assemble_protocol_deconstruction_input,
    build_protocol_deconstruction_input_package,
)
from .full_protocol_coverage import (
    FullProtocolCoverageError,
    FullProtocolCoverageResolutionIssue,
    FullProtocolCoverageResolutionView,
    build_full_protocol_coverage_manifest,
    build_resolved_full_protocol_coverage_view,
    expand_projection_structure_refs,
    resolve_full_protocol_coverage,
)
from .protocol_control_planning import (
    ProtocolControlPlanningError,
    build_protocol_control_batch_plan,
    build_protocol_control_batches,
    plan_protocol_control_batches,
)
from .protocol_control_gate import (
    CONTROL_PUBLICATION_GATE_VERSION,
    ProtocolControlGateError,
    ProtocolControlGateIssue,
    ProtocolControlGateReport,
    check_protocol_control_publication,
    validate_protocol_control_publication,
)
from .protocol_control_matrix import (
    CONTROL_MATRIX_VALIDATOR_VERSION,
    ProtocolControlMatrixError,
    ProtocolControlMatrixIssue,
    ProtocolControlMatrixReport,
    build_protocol_control_matrix_json,
    check_protocol_control_matrix,
    render_protocol_control_matrix_markdown,
    validate_protocol_control_matrix,
    validate_protocol_control_matrix_serializations,
)
from .phase_applicability import (
    PHASE_APPLICABILITY_GATE_VERSION,
    PhaseApplicabilityGateError,
    PhaseApplicabilityGateIssue,
    PhaseApplicabilityGateReport,
    PhaseApplicabilityHydrationError,
    check_phase_applicability_gate,
    check_phase_applicability_resolution,
    gate_phase_applicability_resolution,
    hydrate_phase_applicability_resolution,
    record_phase_applicability_manual_override,
    validate_phase_applicability_resolution,
)
from .phase_applicability_planning import (
    PHASE_APPLICABILITY_DEFAULT_BATCH_PACKING_POLICY,
    PHASE_APPLICABILITY_PLAN_V1_VERSION,
    PHASE_APPLICABILITY_PLAN_V2_VERSION,
    PHASE_APPLICABILITY_PLAN_VERSION,
    PHASE_APPLICABILITY_SAME_HEADING_BATCH_PACKING_POLICY,
    PhaseApplicabilityContextCatalog,
    PhaseApplicabilityFrozenPlan,
    PhaseApplicabilityPlanningError,
    build_phase_applicability_batches,
    build_phase_applicability_frozen_packages,
    build_phase_applicability_plan,
    build_phase_applicability_context_catalog,
    plan_phase_applicability_packages,
    plan_phase_applicability_batches,
)

__all__ = [
    "AlignmentResult",
    "BlockKind",
    "HeaderFooterKind",
    "NumberingRef",
    "ProtocolFileKind",
    "RenderResult",
    "SourceIngestionError",
    "StructureBlock",
    "StructureExtraction",
    "align_blocks",
    "block_set_hash",
    "build_render_artifact",
    "compute_sha256",
    "detect_format",
    "extract_docx_structure",
    "find_block_by_ref",
    "libreoffice_version",
    "locate_libreoffice",
    "parse_numbering",
    "pdf_page_count",
    "pdf_page_texts",
    "register_source_artifact",
    "render_to_pdf",
    "serialize_blocks",
    "utc_now",
    "verify_excerpt_against_blocks",
    "MetadataExtractionError",
    "MetadataExtractionResult",
    "confirm_protocol_identity",
    "extract_metadata_candidates",
    "extract_protocol_metadata",
    "resolve_identity_candidates",
    "resolve_protocol_identity",
    "PhaseDetectionResult",
    "build_phase_applicability_graph",
    "detect_phase_applicability",
    "project_phase_applicability",
    "project_single_phase",
    "DeconstructionInputAssemblyError",
    "ProtocolDeconstructionInputAssembler",
    "ProtocolDeconstructionInputAssemblyError",
    "ProtocolDeconstructionInputPackage",
    "ProtocolInputAssemblyError",
    "assemble_deconstruction_input_package",
    "assemble_protocol_deconstruction_input",
    "build_protocol_deconstruction_input_package",
    "FullProtocolCoverageError",
    "FullProtocolCoverageResolutionIssue",
    "FullProtocolCoverageResolutionView",
    "build_full_protocol_coverage_manifest",
    "build_resolved_full_protocol_coverage_view",
    "expand_projection_structure_refs",
    "resolve_full_protocol_coverage",
    "ProtocolControlPlanningError",
    "build_protocol_control_batch_plan",
    "build_protocol_control_batches",
    "plan_protocol_control_batches",
    "CONTROL_PUBLICATION_GATE_VERSION",
    "ProtocolControlGateError",
    "ProtocolControlGateIssue",
    "ProtocolControlGateReport",
    "check_protocol_control_publication",
    "validate_protocol_control_publication",
    "CONTROL_MATRIX_VALIDATOR_VERSION",
    "ProtocolControlMatrixError",
    "ProtocolControlMatrixIssue",
    "ProtocolControlMatrixReport",
    "build_protocol_control_matrix_json",
    "check_protocol_control_matrix",
    "render_protocol_control_matrix_markdown",
    "validate_protocol_control_matrix",
    "validate_protocol_control_matrix_serializations",
    "PHASE_APPLICABILITY_GATE_VERSION",
    "PHASE_APPLICABILITY_DEFAULT_BATCH_PACKING_POLICY",
    "PHASE_APPLICABILITY_PLAN_V1_VERSION",
    "PHASE_APPLICABILITY_PLAN_V2_VERSION",
    "PhaseApplicabilityGateError",
    "PhaseApplicabilityGateIssue",
    "PhaseApplicabilityGateReport",
    "PhaseApplicabilityHydrationError",
    "check_phase_applicability_gate",
    "check_phase_applicability_resolution",
    "gate_phase_applicability_resolution",
    "hydrate_phase_applicability_resolution",
    "record_phase_applicability_manual_override",
    "validate_phase_applicability_resolution",
    "PHASE_APPLICABILITY_PLAN_VERSION",
    "PHASE_APPLICABILITY_SAME_HEADING_BATCH_PACKING_POLICY",
    "PhaseApplicabilityContextCatalog",
    "PhaseApplicabilityFrozenPlan",
    "PhaseApplicabilityPlanningError",
    "build_phase_applicability_batches",
    "build_phase_applicability_frozen_packages",
    "build_phase_applicability_plan",
    "build_phase_applicability_context_catalog",
    "plan_phase_applicability_packages",
    "plan_phase_applicability_batches",
]
