// @vitest-environment jsdom

import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, describe, expect, it, vi } from "vitest";
import type { FactCorrectionHistoryView } from "../../api/patient-profile";
import {
  decodePatientProfileRevision,
  setPatientProfileRepository,
  type PatientProfileRepository,
} from "../../api/patient-profile";
import {
  makeFactItem,
  makeLaneSection,
  makeLocator,
  makeRevision,
  PROFILE_LANE_ORDER,
} from "../../api/patient-profile/patientProfileFixtures";
import { adaptPatientProfile } from "../../features/patient-profile/model";
import { ProfileCorrectionHistory } from "./ProfileCorrectionHistory";

const SUBJECT = "subject-1";
/** 修订生成后的档案标题/摘录（与 patient_profile_revision_id 绑定）。 */
const GENERATED_TITLE = "血压 130/85 mmHg";
const GENERATED_EXCERPT = "基线血压 130/85 mmHg";
/** 修订前档案使用不同 locator id；同一 id 不得跨页解析。 */
const PRE_CORRECTION_TITLE = "血压 120/80 mmHg";
const PRE_CORRECTION_EXCERPT = "基线血压 120/80 mmHg";
const CITED_LOCATOR_ID = "loc-bp-1";
const PRE_CORRECTION_LOCATOR_ID = "loc-bp-pre";

function lanesWithFact(
  title: string,
  value: string,
  locatorIds: string[],
  sourceId = "fact-source-2",
) {
  return PROFILE_LANE_ORDER.map((lane) => {
    if (lane === "demographics") {
      return makeLaneSection(lane, [
        makeFactItem({
          source_id: sourceId,
          title,
          value,
          locator_ids: locatorIds,
        }),
      ]);
    }
    return makeLaneSection(lane, []);
  });
}

/** 本次修订生成的档案：新值 + 提交时引用的定位。 */
function generatedWire() {
  return makeRevision({
    patient_profile_revision_id: "profile-revision-3",
    revision: 3,
    lanes: lanesWithFact(GENERATED_TITLE, "130/85", [CITED_LOCATOR_ID]),
    highlights: [],
    evidence_locators: [
      makeLocator({
        locator_id: CITED_LOCATOR_ID,
        page_number: 1,
        excerpt: GENERATED_EXCERPT,
        precision_label: "原文区域",
      }),
    ],
  });
}

function history(): FactCorrectionHistoryView {
  const dateRange = {
    source_text: "2026-03",
    precision: "month",
    lower_bound: "2026-03-01",
    upper_bound: "2026-03-31",
  };
  const snapshot = (value: string) => ({
    kind: "fact",
    fact_type: "vital_sign",
    profile_lane: "demographics",
    polarity: "affirmed",
    asserted_object: "血压",
    value,
    unit: "mmHg",
    date_range: dateRange,
    source_strength: "current_study_chart_direct_record",
    assertion_object: "血压",
    assertion_text: `基线血压 ${value} mmHg`,
    supported_requirement_ids: ["req-1"],
  });
  return {
    subjectId: SUBJECT,
    reviewEpisodeId: "episode-1",
    items: [
      {
        correctionId: "correction-1",
        targetKind: "fact",
        targetKindLabel: "事实",
        targetId: "fact-source-1",
        newEntityId: "fact-source-2",
        reason: "原始报告数值与当前记录不一致。",
        operatorId: "local-reviewer",
        locatorIds: [CITED_LOCATOR_ID],
        correctedAt: "2026-08-23T08:00:00Z",
        oldSnapshot: snapshot("120/80"),
        newSnapshot: snapshot("130/85"),
        impact: {
          scopeKind: "local",
          scopeKindLabel: "当前记录及相关内容",
          fallbackReason: null,
          affectedLocatorIds: [CITED_LOCATOR_ID],
          affectedDocumentIds: ["document-1"],
          affectedFactIds: ["fact-source-1"],
          affectedEventIds: [],
          affectedExposureIds: [],
          affectedConflictGroupIds: ["conflict-1"],
          affectedRuleLinkIds: [],
          affectedExpectationIds: [],
          affectedProfileRevisionIds: ["profile-revision-1"],
        },
        profileRevisionId: "profile-revision-3",
        profileRevision: 3,
      },
    ],
  };
}

function makeRepo(
  getRevision: PatientProfileRepository["getPatientProfileRevision"],
): PatientProfileRepository {
  return {
    kind: "http",
    getLatestPatientProfile: vi.fn(() =>
      Promise.resolve(decodePatientProfileRevision(generatedWire())),
    ),
    listPatientProfileHistory: vi.fn(),
    getPatientProfileRevision: getRevision,
    previewFactCorrection: vi.fn(),
    submitFactCorrection: vi.fn(),
    listFactCorrectionHistory: vi.fn(),
    getFactCorrectionJobStatus: vi.fn(),
    cancelFactCorrectionJob: vi.fn(),
    retryFactCorrectionJob: vi.fn(),
  };
}

describe("ProfileCorrectionHistory", () => {
  afterEach(() => {
    setPatientProfileRepository(null);
  });

  it("renders title and locator from the Profile generated by the correction", async () => {
    const getRevision = vi.fn(async (_subjectId: string, revisionId: string) => {
      expect(revisionId).toBe("profile-revision-3");
      return decodePatientProfileRevision(generatedWire());
    });
    setPatientProfileRepository(makeRepo(getRevision));

    render(
      <ProfileCorrectionHistory
        state={{ status: "success", data: history() }}
        subjectId={SUBJECT}
      />,
    );

    expect(await screen.findByText(GENERATED_TITLE)).toBeInTheDocument();
    expect(
      screen.getByText(`第 1 页 · 原文区域 · “${GENERATED_EXCERPT}”`),
    ).toBeInTheDocument();
    expect(screen.queryByText(PRE_CORRECTION_TITLE)).not.toBeInTheDocument();
    expect(screen.queryByText(PRE_CORRECTION_EXCERPT)).not.toBeInTheDocument();
    expect(screen.getByText("本次修订形成档案第 3 版。")).toBeInTheDocument();
    expect(screen.getByText("受影响历史档案")).toBeInTheDocument();
    expect(getRevision).toHaveBeenCalledWith(
      SUBJECT,
      "profile-revision-3",
      expect.objectContaining({ signal: expect.any(AbortSignal) }),
    );
  });

  it("opens original evidence with the generated Profile model snapshot", async () => {
    const user = userEvent.setup();
    const getRevision = vi.fn(async () =>
      decodePatientProfileRevision(generatedWire()),
    );
    setPatientProfileRepository(makeRepo(getRevision));
    const onOpenEvidence = vi.fn();
    const generatedModel = adaptPatientProfile(
      decodePatientProfileRevision(generatedWire()),
    );

    render(
      <ProfileCorrectionHistory
        state={{ status: "success", data: history() }}
        subjectId={SUBJECT}
        onOpenEvidence={onOpenEvidence}
      />,
    );

    await screen.findByText(GENERATED_TITLE);
    await user.click(screen.getByRole("button", { name: "查看原文" }));

    expect(onOpenEvidence).toHaveBeenCalledTimes(1);
    const [item, model] = onOpenEvidence.mock.calls[0]!;
    expect(item.title).toBe(GENERATED_TITLE);
    expect(model.revisionId).toBe("profile-revision-3");
    expect(model.locatorById.get(CITED_LOCATOR_ID)?.excerpt).toBe(GENERATED_EXCERPT);
    expect(model.locatorById.has(PRE_CORRECTION_LOCATOR_ID)).toBe(false);
    expect(model.revisionId).toBe(generatedModel.revisionId);
  });

  it("does not fall back to latest when the generated Profile cannot be loaded", async () => {
    const getRevision = vi.fn(async () => {
      throw new Error("revision missing");
    });
    setPatientProfileRepository(makeRepo(getRevision));

    render(
      <ProfileCorrectionHistory
        state={{ status: "success", data: history() }}
        subjectId={SUBJECT}
      />,
    );

    await waitFor(() => {
      expect(screen.getByRole("alert")).toBeInTheDocument();
    });
    expect(screen.queryByText(GENERATED_TITLE)).not.toBeInTheDocument();
    expect(screen.queryByText(PRE_CORRECTION_TITLE)).not.toBeInTheDocument();
  });
});
