"""Phase 4 证据处理工具包（Slice 4.0 纯函数 + Slice 4.3 页产物/OCR 适配器）。

Slice 4.0 冻结的纯确定性模块：坐标系统换算、识别配置指纹、pdfplumber 原生提取、
诚实定位器、风险扫描、验收度量、逐格式分页与确定性页图渲染。

Slice 4.3（worker_02）扩展：不可变内容寻址工件库（``artifacts``）、冻结
text-only OCR 适配器与页级缓存（``ocr_adapter``）、逐页路由与页产物生成
（``page_processor``）与 LibreOffice 文档转换（``doc_converter``）。这些模块
触及 V2 数据根与 OCR 仓储（区别于 Slice 4.0 纯函数层），但同样不实现
页工作租约/共享 oMLX 门禁/运行编排（worker_03）。
"""
from __future__ import annotations

from . import (
    artifacts,
    coordinates,
    doc_converter,
    effective_text,
    eval,
    fingerprint,
    goldset,
    locator,
    ocr_adapter,
    page_processor,
    paging,
    pdf_native,
    render,
    risk,
    selective_vision_review,
    text,
)
from .coordinates import (
    COORDINATE_TRANSFORM_VERSION,
    CoordinateError,
    bbox_contains,
    bbox_overlap_ratio,
    image_pixels_to_pdf_points,
    pdf_points_to_image_pixels,
)
from .effective_text import (
    EffectiveTextProjection,
    ProjectionOverlapError,
    project_effective_text,
)
from .eval import (
    LayoutCandidate,
    LayoutEval,
    LocatorEval,
    ReadbackEval,
    RiskEval,
    evaluate_layout_candidates,
    evaluate_locators,
    evaluate_readback,
    evaluate_risk_seed,
    target_locator_success,
)
from .fingerprint import (
    build_ocr_cache_key,
    build_profile_fingerprint,
    content_sha256,
    page_artifact_identity_hash,
    page_derivative_hash,
)
from .goldset import GoldPage, GoldSet, GoldTarget, precision_rank
from .locator import (
    LOCATOR_ALGORITHM_VERSION,
    find_all_whitespace_insensitive,
    locate_target,
)
from .ocr_adapter import (
    DEFAULT_PROMPT,
    INFERENCE_FAILURE_REASON,
    TEXT_ONLY_DEGRADATION_REASON,
    InferenceResult,
    OcrAdapterError,
    OcrCacheIdentityError,
    OcrFailure,
    OcrRecognition,
    PreparedOcrRequest,
    TextOnlyOcrAdapter,
    build_ocr_page,
    build_ocr_request_payload,
)
from .page_processor import (
    DECODER_VERSION_BY_KIND,
    PageArtifactOutcome,
    PageProcessorError,
    build_page_artifact,
    decide_route,
    decide_route_detailed,
    process_source,
)
from .paging import (
    PAGING_VERSION,
    SUPPORTED_MEDIA_KINDS,
    DocConversionError,
    DocConverter,
    PageInput,
    PagePlan,
    PagingError,
    derived_doc_input_sha256,
    is_tiff,
    page_source_document,
)
from .pdf_native import (
    NativeChar,
    NativePage,
    NativeWord,
    extract_native_page,
    serialize_native_coordinates,
)
from .render import (
    RENDER_DPI,
    RENDERER_VERSION,
    RenderedPage,
    RenderError,
    render_page_image,
)
from .risk import (
    OCR_RISK_LEVEL_MATRIX,
    OCR_RISK_RULE_VERSION,
    scan_ocr_risks,
    would_block_activation,
)
from .selective_vision_review import (
    SELECTIVE_VISION_PLAN_VERSION,
    PageVisionEligibility,
    PageVisionTriageSignals,
    SelectiveVisionClosedError,
    SelectiveVisionPlan,
    SelectiveVisionReviewOutcome,
    assess_page_vision_eligibility,
    plan_selective_vision_reviews,
    run_selective_vision_review,
)
from .text import DecodedText, TextDecodeError, decode_text_bytes

__all__ = [
    "COORDINATE_TRANSFORM_VERSION",
    "DECODER_VERSION_BY_KIND",
    "DEFAULT_PROMPT",
    "INFERENCE_FAILURE_REASON",
    "LOCATOR_ALGORITHM_VERSION",
    "OCR_RISK_LEVEL_MATRIX",
    "OCR_RISK_RULE_VERSION",
    "PAGING_VERSION",
    "RENDERER_VERSION",
    "RENDER_DPI",
    "SELECTIVE_VISION_PLAN_VERSION",
    "SUPPORTED_MEDIA_KINDS",
    "TEXT_ONLY_DEGRADATION_REASON",
    "CoordinateError",
    "DecodedText",
    "DocConversionError",
    "DocConverter",
    "EffectiveTextProjection",
    "GoldPage",
    "GoldSet",
    "GoldTarget",
    "InferenceResult",
    "LayoutCandidate",
    "LayoutEval",
    "LocatorEval",
    "NativeChar",
    "NativePage",
    "NativeWord",
    "OcrAdapterError",
    "OcrCacheIdentityError",
    "OcrFailure",
    "OcrRecognition",
    "PageArtifactOutcome",
    "PageInput",
    "PagePlan",
    "PageProcessorError",
    "PageVisionEligibility",
    "PageVisionTriageSignals",
    "PagingError",
    "PreparedOcrRequest",
    "ProjectionOverlapError",
    "ReadbackEval",
    "RenderError",
    "RenderedPage",
    "RiskEval",
    "SelectiveVisionClosedError",
    "SelectiveVisionPlan",
    "SelectiveVisionReviewOutcome",
    "TextDecodeError",
    "TextOnlyOcrAdapter",
    "artifacts",
    "assess_page_vision_eligibility",
    "bbox_contains",
    "bbox_overlap_ratio",
    "build_ocr_cache_key",
    "build_ocr_page",
    "build_ocr_request_payload",
    "build_page_artifact",
    "build_profile_fingerprint",
    "content_sha256",
    "coordinates",
    "decide_route",
    "decide_route_detailed",
    "decode_text_bytes",
    "derived_doc_input_sha256",
    "doc_converter",
    "effective_text",
    "eval",
    "evaluate_layout_candidates",
    "evaluate_locators",
    "evaluate_readback",
    "evaluate_risk_seed",
    "extract_native_page",
    "find_all_whitespace_insensitive",
    "fingerprint",
    "goldset",
    "image_pixels_to_pdf_points",
    "is_tiff",
    "locate_target",
    "locator",
    "ocr_adapter",
    "page_artifact_identity_hash",
    "page_derivative_hash",
    "page_processor",
    "page_source_document",
    "paging",
    "pdf_native",
    "pdf_points_to_image_pixels",
    "plan_selective_vision_reviews",
    "precision_rank",
    "process_source",
    "project_effective_text",
    "render",
    "render_page_image",
    "risk",
    "run_selective_vision_review",
    "scan_ocr_risks",
    "selective_vision_review",
    "serialize_native_coordinates",
    "target_locator_success",
    "text",
    "would_block_activation",
]
